bracketSpacing: true
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false

overrides:
  - files: "*.md"
    options:
      printWidth: 150
  - files: "*.sol"
    options:
      compiler: "0.8.17"
      printWidth: 132
      tabWidth: 4
