export enum PanicCodes {
  ArithmeticOverflowOrUnderflow = "0x11",
  DivisionByZero = "0x12",
}

export enum PRBMathErrors {
  AbsInputTooSmall = "AbsInputTooSmall",
  AddUd60x18Overflow = "AddUd60x18Overflow",
  CeilSd59x18Overflow = "CeilSd59x18Overflow",
  CeilUd60x18Overflow = "CeilUd60x18Overflow",
  DivSd59x18InputTooSmall = "DivSd59x18InputTooSmall",
  DivSd59x18Overflow = "DivSd59x18Overflow",
  ExpInputTooBig = "ExpInputTooBig",
  Exp2InputTooBig = "Exp2InputTooBig",
  FloorSd59x18Underflow = "FloorSd59x18Underflow",
  FromIntOverflow = "FromIntOverflow",
  FromIntUnderflow = "FromIntUnderflow",
  FromUintOverflow = "FromUintOverflow",
  GmNegativeProduct = "GmNegativeProduct",
  GmSd59x18Overflow = "GmSd59x18Overflow",
  GmUd60x18Overflow = "GmUd60x18Overflow",
  LogSd59x18InputTooSmall = "LogSd59x18InputTooSmall",
  LogUd60x18InputTooSmall = "LogUd60x18InputTooSmall",
  MulDivFixedPointOverflow = "MulDivFixedPointOverflow",
  MulDivOverflow = "MulDivOverflow",
  MulDivSignedInputTooSmall = "MulDivSignedInputTooSmall",
  MulDivSignedOverflow = "MulDivSignedOverflow",
  MulSd59x18InputTooSmall = "MulSd59x18InputTooSmall",
  MulSd59x18Overflow = "MulSd59x18Overflow",
  PowuSd59x18Overflow = "PowuSd59x18Overflow",
  SqrtSd59x18NegativeInput = "SqrtSd59x18NegativeInput",
  SqrtSd59x18Overflow = "SqrtSd59x18Overflow",
  SqrtUd60x18Overflow = "SqrtUd60x18Overflow",
  SubUnderflowUd60x18 = "SubUnderflowUd60x18",
}
